services:

  postgres-auth:
    image: postgres:15
    container_name: postgres-auth
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: auth
    ports:
      - "5432:5432"
    volumes:
      - pg-auth-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auth"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - bank-network

  postgres-card:
    image: postgres:15
    container_name: postgres-card
    environment:
      POSTGRES_DB: card
      POSTGRES_USER: card
      POSTGRES_PASSWORD: card
    ports:
      - "5433:5432"
    volumes:
      - pg-card-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U card" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - bank-network

  postgres-transfer:
    image: postgres:15
    container_name: postgres-transfer
    environment:
      POSTGRES_DB: transfer
      POSTGRES_USER: transfer
      POSTGRES_PASSWORD: transfer
    ports:
      - "5434:5432"
    volumes:
      - pg-transfer-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U transfer" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - bank-network

  postgres-user:
    image: postgres:15
    container_name: postgres-user
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    ports:
      - "5435:5432"
    volumes:
      - pg-user-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d userdb" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - bank-network

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    container_name: api-gateway
    depends_on:
      auth-service:
        condition: service_started
    ports:
      - "8080:8080"
    networks:
      - bank-network

  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    container_name: auth-service
    depends_on:
      postgres-auth:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-auth:5432/auth
      SPRING_DATASOURCE_USERNAME: auth
      SPRING_DATASOURCE_PASSWORD: auth
    ports:
      - "8081:8081"
    networks:
      - bank-network

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    container_name: user-service
    depends_on:
      postgres-user:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-user:5432/userdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: user
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://auth-service:8081/auth/jwks
    ports:
      - "8082:8082"
    networks:
      - bank-network

  card-service:
    build:
      context: .
      dockerfile: card-service/Dockerfile
    container_name: card-service
    depends_on:
      postgres-card:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-card:5432/card
      SPRING_DATASOURCE_USERNAME: card
      SPRING_DATASOURCE_PASSWORD: card
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://auth-service:8081/auth/jwks
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8083:8083"
    networks:
      - bank-network

  transfer-service:
    build:
      context: .
      dockerfile: transfer-service/Dockerfile
    container_name: transfer-service
    depends_on:
      postgres-transfer:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-transfer:5432/transfer
      SPRING_DATASOURCE_USERNAME: transfer
      SPRING_DATASOURCE_PASSWORD: transfer
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://auth-service:8081/auth/jwks
    ports:
      - "8084:8084"
    networks:
      - bank-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - bank-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    volumes:
      - kafka-data:/var/lib/kafka/data
    healthcheck:
      test: [ "CMD", "bash", "-c", "kafka-topics --bootstrap-server localhost:9092 --list" ]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - bank-network

networks:
  bank-network:
    driver: bridge

volumes:
  pg-auth-data:
  pg-card-data:
  pg-transfer-data:
  pg-user-data:
  kafka-data: