server:
  port: 8080

spring:
  application:
    name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://auth-service:8081/auth/jwks

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

  cloud:
    gateway:
      httpclient:
        connect-timeout: 3000
        response-timeout: 5s
        pool:
          max-idle-time: 5000
      default-filters:
        - RemoveRequestHeader=Cookie
      forwarded:
        enabled: true

      routes:
        - id: auth-api-docs
          uri: http://auth-service:8081
          predicates:
            - Path=/auth/v3/api-docs
          filters:
            - RewritePath=/auth/(?<segment>.*), /$\{segment}

        - id: users-api-docs
          uri: http://user-service:8082
          predicates:
            - Path=/users/v3/api-docs
          filters:
            - RewritePath=/users/(?<segment>.*), /$\{segment}

        - id: cards-api-docs
          uri: http://card-service:8083
          predicates:
            - Path=/cards/v3/api-docs
          filters:
            - RewritePath=/cards/(?<segment>.*), /$\{segment}

        - id: transfers-api-docs
          uri: http://transfer-service:8084
          predicates:
            - Path=/transfers/v3/api-docs,/analytics/v3/api-docs
          filters:
            - RewritePath=/transfers/(?<segment>.*), /$\{segment}


        - id: auth
          uri: http://auth-service:8081
          predicates:
            - Path=/auth/**

        - id: users
          uri: http://user-service:8082
          predicates:
            - Path=/users/**

        - id: cards
          uri: http://card-service:8083
          predicates:
            - Path=/cards/**

        - id: transfers
          uri: http://transfer-service:8084
          predicates:
            - Path=/transfers/**,/analytics/**

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO
    reactor.netty.http.client: WARN

springdoc:
  swagger-ui:
    urls:
      - name: auth
        url: /auth/v3/api-docs
      - name: users
        url: /users/v3/api-docs
      - name: cards
        url: /cards/v3/api-docs
      - name: transfers
        url: /transfers/v3/api-docs
    disable-swagger-default-url: true
    path: /swagger-ui.html
