server:
  port: 8084
  forward-headers-strategy: framework

spring:
  application:
    name: transfer-service

  datasource:
    url: jdbc:postgresql://postgres-transfer:5432/transfer
    username: transfer
    password: transfer
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://auth-service:8081/auth/jwks
      client:
        registration:
          card-service:
            client-id: ${INTERNAL_CLIENT_TRANSFER_SERVICE_ID:transfer-service}
            client-secret: ${INTERNAL_CLIENT_TRANSFER_SERVICE_SECRET:default-secret}
            authorization-grant-type: client_credentials
            scope: internal
        provider:
          card-service:
            token-uri: http://auth-service:8081/auth/oauth/token

  kafka:
    bootstrap-servers: kafka:9092
    admin:
      auto-create: true
    consumer:
      group-id: transfer-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

feign:
  httpclient:
    enabled: true

logging:
  level:
    root: INFO