server:
  port: 8083

spring:
  application:
    name: card-service

#  datasource:
#    url: jdbc:postgresql://postgres-auth:5432/auth
#    username: auth
#    password: auth
#    driver-class-name: org.postgresql.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: validate
#    show-sql: false
#    open-in-view: false
#
#  liquibase:
#    enabled: true
#    change-log: classpath:db/changelog/db.changelog-master.yaml
#
#  security:
#    user:
#      name: disabled
#      password: disabled

logging:
  level:
    root: INFO